class DataIngestionArtifact:
    pass
class DataValidationArtifact:...
class DataTransaformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
